name: Send Latest Invoice
on:
  schedule:
    # 6 am MST (12 pm UTC) first day of every month
    - cron:  '0 12 1 */1 *'
  
jobs:
  sendInvoice:
    env:
      AVAZA_TOKEN: ${{secrets.AVAZA_TOKEN}}
      MAIL_DEFAULT_SENDER: ${{secrets.MAIL_DEFAULT_SENDER}}
      MAIL_TEST_RECIPIENT: ${{secrets.MAIL_TEST_RECIPIENT}}
      MAIL_BCC: ${{secrets.MAIL_BCC}}
      SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}

    name: Send Latest Invoice
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
          
      - name: Install Dependencies
        run: npm install

      - name: Send It!
        run: node scripts/sendLatestInvoice.js test=false
