name: GH Actions Cron Schedule
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 * * * *'
  
jobs:
  sendInvoice:
    name: Send Latest Invoice
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
          
      - name: Install Dependencies
        run: npm install

      - name: Send It!
        run: node scripts/sendLatestInvoice.js test=true sendTo=cheetolick311@gmail.com
